apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accounts-and-transfers
  name: accounts-and-transfers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-and-transfers
  template:
    metadata:
      labels:
        app: accounts-and-transfers
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: localhost:32000/accounts-and-transfers:latest
          imagePullPolicy: "Always"
          name: accounts-and-transfers
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-0.mongodb-headless.default.svc.cluster.local:27017/accounts-and-transfers"
            - name: RABBITMQ_URI
              value: "amqp://user:JwSmlVml6BFfibCj@rabbitmq.default.svc.cluster.local:5672"